packages:
  # all packages in direct subdirs of packages/
  - 'packages/*'
  # all packages in direct subdirs of templates/
  - 'templates/*'
  # all packages in direct subdirs of examples/
  - 'examples/*'
